client_ticket_order:
    resource: "@ClientTicketBundle/Resources/config/routing/ordering.yml"
    prefix:   /order

ticket_list:
    path:     /
    defaults: { _controller: ClientTicketBundle:Default:list }

ticket_add:
    path:     /add
    defaults: { _controller: ClientTicketBundle:Default:add }