ordering_index:
    path:     /
    defaults: { _controller: "ClientTicketBundle:Ordering:index" }
    methods:  GET

ordering_show:
    path:     /{id}/show
    defaults: { _controller: "ClientTicketBundle:Ordering:show" }
    methods:  GET

ordering_new:
    path:     /new
    defaults: { _controller: "ClientTicketBundle:Ordering:new" }
    methods:  [GET, POST]

ordering_edit:
    path:     /{id}/edit
    defaults: { _controller: "ClientTicketBundle:Ordering:edit" }
    methods:  [GET, POST]

ordering_delete:
    path:     /{id}/delete
    defaults: { _controller: "ClientTicketBundle:Ordering:delete" }
    methods:  DELETE
